test/e2e/17.0/jwsserver_test.go
test/framework/common.go

Arrange the logic to have the parameters wsserver_test.go to make

---

Makefile
deploy/role.yaml
deploy/role_binding.yaml
pkg/controller/webserver/webserver_controller.go

the DNSPing uses a service and dns (dns  means problems :D), KUBEPing uses the kubernetes api to read the nodes that should be more reliable when scaling up.

Default to KUBEPing if the permissions are correct.

---

Makefile
test/e2e/5/jwsserver_test.go
test/framework/common.go
test/framework/webserver.go

Improved test error tracking
Prevented test cleanup in case of error
Refactord test code
Set test namespace to jws-e2e-tests
Added method that retries for Route detection

Splits test into smaller ones

---

deploy/crds/web.servers.org_webservers_cr_build_webapp_full.yaml
deploy/crds/web.servers.org_webservers_cr_build_webapp_minimal.yaml
go.mod
pkg/apis/webservers/v1alpha1/webserver_types.go
pkg/controller/webserver/webserver_controller.go

Added a functionality that enables users to automatically build and deploy their webapp when using the application image method

Webapp build on application image deployment

---

test/scripts/README.md
test/scripts/test-jws_src_test_resources_operators_jws_update-yaml-files.sh

https://issues.redhat.com/browse/JWS-1868 use a "non-admin" user to install the operator

---

Makefile
controllers/helper.go
controllers/other_basic_test.go
controllers/suite_test.go
controllers/templates.go
controllers/webServerApplicationImageBasic_test.go
controllers/webserver_controller.go
test/framework/common.go

Add hash to control the rebuilds/redeployments on kubernetes.
Add LoadBalancer on kuberntes and adjust the tests to run on kubernetes

Add hash to control the rebuilds/redeployments on kubernetes and add LoadBalancer.

---

Makefile
README.md

@jfclere  please review and merge, Thank you.

Go get depr

---

controllers/basic_test.go
controllers/helper.go
controllers/other_basic_test.go
controllers/suite_test.go

deleted unnecessary/confusing commented code

unnecessary comments

---

api/v1alpha1/webserver_types.go
config/crd/bases/web.servers.org_webservers.yaml
controllers/templates.go
controllers/webserver_controller.go

This PR contains implementation of automated secure route's creation, code for mounting the secret created by user to the pod and script for editing the server.xml in order to create the secure route. 
Cotnributes to: https://github.com/web-servers/jws-operator/issues/61
Signed-off: [vmouriki@gmail.com](mailto:vmouriki@gmail.com)

control secure route creation

---

controllers/helper.go
controllers/webserver_controller.go

The problem is that:
r.Client.Update(context.TODO(), webServer) 
was not working :-(

More for for https://github.com/web-servers/jws-operator/issues/80

---

README.md
api/v1alpha1/webserver_types.go
controllers/templates.go
controllers/webServerApplicationImageBasic_test.go
test/framework/common.go
test/framework/webserver.go

Tests for the secure route creation.
Cotnributes to: https://github.com/web-servers/jws-operator/issues/73
Signed-off: [vmouriki@gmail.com](mailto:vmouriki@gmail.com)

secure route's tests

---

controllers/helper.go
controllers/webserver_controller.go

Fix for [JWS-2544](https://issues.redhat.com/browse/JWS-2544)
Cotnributes to: https://github.com/web-servers/jws-operator/issues/73

fix for JWS-2544

---

controllers/helper.go
controllers/label_test.go
controllers/webserver_controller.go

Finished label_test.go that was testing nothing before and added webserver-hash in the DeploymentConfig.

webserver-hash and label_test

---

controllers/basic_test.go
controllers/label_test.go
controllers/webServerApplicationImageBasic_test.go

Added checks for imagestream and secret needed for the tests. Fixed label_test and added extra test for the webimagestream.

imagestream and secret checks and lebel test fixed

---

controllers/webserver_controller.go

It seems I commented the missing part in the past, sorry my bad.

Fix for https://issues.redhat.com/browse/JWS-2550

---

controllers/webServerApplicationImageBasic_test.go
controllers/webserver_controller.go

Removed some unused code and changed the way we check imagestream existance.

cleaning tests

---

controllers/label_test.go

problem causing the loop

---

controllers/suite_test.go

added useExistingCluster variable

fixed realtests

---

.github/workflows/test.yml

Added a github action which executes basic tests for every push/pull request.

Add github action for basic tests

---

controllers/webServerApplicationImageBasic_test.go
test/framework/common.go

[Add] Added test for Horizontal Pod Autoscaler as refers in [JWS-2335](https://issues.redhat.com/browse/JWS-2335).

test for Horizontal Pod Autoscaler JWS-2335

---

controllers/templates.go

[Fix] generateCustomProbe() which was generating the command wrongly due to wrong positioning.

fix generateCustomProbe()

---

controllers/templates.go

[Fix] the wrong order that caused from the conflict resolution and broke the file name.

fix wrong order

---

controllers/templates.go
controllers/webserver_controller.go

[Fix] for failing probe propagation via operator. Added logic in which the commands that user inserts as a parameter are copied to a script inside a ConfigMap mounded to the created pods.
Cotnributes to: https://github.com/web-servers/jws-operator/issues/118

Probes fix

---

controllers/webServerApplicationImageBasic_test.go
test/framework/common.go

[Add] Tests for persistent logs feature.

persistent logs test

---

controllers/webserver_controller.go

[Fix] Where the implementation was placed needed useSessionClustering enabled in order to work and that's irrelevant with the feature so I excluded it from this if statement.

wrong code placement

---

controllers/label_test.go

[Fix] label test replacing update with patch operation to avoid "object has been modified" errors.

fix label test flackiness

---

controllers/suite_test.go

just a work-around for something wrong in  kube-apiserver...

Work around for https://github.com/kubernetes-sigs/controller-runtime/issues/1571

---

controllers/templates.go
controllers/webServerApplicationImageBasic_test.go
controllers/webserver_controller.go
test/framework/common.go

[Add] needed config map generation for [JWS-2415](https://issues.redhat.com/browse/JWS-2415) and the appropriate tests.

add configmap generation and tests for prometheus feature 

---

test/framework/common.go

[Fix] Fixed Prometheus test to stop using token for authentication in order to work in every cluster provider. We are using prometheus dashboard to test it now.
Cotnributes to: https://github.com/web-servers/jws-operator/issues/127

fix prometheus test

---

Makefile

Makefile extention about new targets

Makefile extention about new targets

---

controllers/basic_test.go
controllers/helper.go
controllers/label_test.go
controllers/webServerApplicationImageBasic_test.go
test/framework/common.go

move images to organization repo

---

controllers/helper.go
controllers/other_basic_test.go
controllers/suite_test.go
controllers/templates.go
controllers/webServerApplicationImageBasic_test.go
controllers/webserver_controller.go
test/framework/common.go
test/framework/webserver.go

Arrange operator and testsuite

---

controllers/suite_test.go
controllers/webServerApplicationImageBasic_test.go

Make sure the tests to have realtest run are in suite_test.go to it fails early.

Move the test for reatest to suite_test.go

---

api/v1alpha1/webserver_types.go
api/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/web.servers.org_webservers.yaml
config/default/manager_auth_proxy_patch.yaml
config/manager/manager.yaml
controllers/suite_test.go
controllers/templates.go

It adds securityContext settings to CRD and sets securityContext for operator pod and application pods.

SecurityContext settings

---

README.md

README extention (multiple installation note)

README extention (multiple installation note)

---

controllers/templates.go

Typo fix in persistance log file name

Typo fix in persistance log file name

---

Parameters.md
controllers/templates.go

Webhook secret logic update.

---

.gitignore
Makefile
README.md
bundle.Dockerfile
bundle/manifests/jws-operator-controller-manager-metrics-service_v1_service.yaml
bundle/manifests/jws-operator-manager-config_v1_configmap.yaml
bundle/manifests/jws-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
bundle/manifests/jws-operator.clusterserviceversion.yaml
bundle/manifests/web.servers.org_webservers.yaml
bundle/metadata/annotations.yaml
bundle/tests/scorecard/config.yaml

Add bundle files

---

bundle/manifests/jws-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/webserver_controller.go

Operator starts updating BuildConfig based on WebServer updates.

Build config

---

controllers/templates.go
controllers/webserver_controller.go

Replacing deprecated DeploymentConfig with Deployment

Replacing deprecated DeploymentConfig with Deployment

---

controllers/label_test.go
controllers/webServerApplicationImageBasic_test.go
test/framework/common.go

Changes needed to get make realtest to pass.

Make realtest to pass.

---

controllers/webserver_controller.go

Better code and it should decrease number of build config updates

Webhook update

---

controllers/templates.go

INSIGHTS_DEBUG added

---

controllers/templates.go

Fix route name

---

Parameters.md

Parameters update

---

README.md
bundle/manifests/jws-operator.clusterserviceversion.yaml
config/default/manager_auth_proxy_patch.yaml
controllers/webServerApplicationImageBasic_test.go

Sync with main

---

bundle/manifests/jws-operator.clusterserviceversion.yaml

Operator bundle allows more install modes

Operator bundle allows more install modes

---

test/scripts/TLS.md

Instructions for preparing test certificats

Instructions for preparing test certificats

---

controllers/helper.go
controllers/templates.go
test/framework/common.go

Replaces deploymentConfig label with deployment

Removes deploymentConfig label

---

api/v1alpha1/webserver_types.go
bundle/manifests/web.servers.org_webservers.yaml
config/crd/bases/web.servers.org_webservers.yaml

Selector is no longer required

Selector is no longer required

---

.gitignore

Add vendor/ among ingored paths in gitignore

---

Makefile

Add a target onetest to use with TEST="Test name", note that is Basic test in:
```
var _ = Describe("WebServer controller", func() {
Context("First Test", func() {
It("Basic test", func() {
```
To run a "single" test use:
`make onetest TEST="Basic Test"`

Allow to run a single test.

---

controllers/webServerApplicationImageBasic_test.go
test/framework/common.go

Generic test for environment variable and test for environment variable requested by insights.

Environment variable test

---

README.md

Updating README with the operator-sdk flag

Updating README with the operator-sdk flag
